# Generated by Django 5.0.4 on 2024-05-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("battle_data", models.DateTimeField(auto_now_add=True)),
                ("battle_time", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game_Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="static/assets/images/")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image_logo", models.ImageField(upload_to="static/assets/images/")),
            ],
        ),
        migrations.CreateModel(
            name="Battle_News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.battle"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Battle_News_Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/assets/images/")),
                (
                    "battle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.battle"
                    ),
                ),
                (
                    "battle_news_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cyber.battle_news",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "founder_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.company"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="battle",
            name="game_club_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cyber.game_club"
            ),
        ),
        migrations.CreateModel(
            name="Gamer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100, unique=True)),
                ("rating", models.IntegerField(default=0)),
                ("avatar", models.ImageField(upload_to="static/assets/avatars/")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gamer_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gamer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.gamer"
                    ),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Battle_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "battle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.battle"
                    ),
                ),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Updates_news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("video", models.FileField(upload_to="static/assets/videos/")),
                ("image", models.ImageField(upload_to="static/assets/images/")),
                (
                    "game_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cyber.game"
                    ),
                ),
            ],
        ),
    ]
