# Generated by Django 5.0.6 on 2024-05-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_alter_group_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle_news_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/'),
        ),
    ]
