# Generated by Django 5.0.6 on 2024-05-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0004_rename_image_battle_news_images_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_club',
            old_name='image',
            new_name='game_club_image',
        ),
        migrations.RenameField(
            model_name='updates_news',
            old_name='image',
            new_name='updates_news_image',
        ),
        migrations.RenameField(
            model_name='updates_news',
            old_name='video',
            new_name='updates_news_video',
        ),
    ]
