# Generated by Django 5.0.6 on 2024-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0005_rename_image_game_club_game_club_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='battle_data',
            field=models.DateTimeField(),
        ),
    ]
